package com.evoluirmais.evoluirmaisapi.model.enums;

public enum Habilidade {

    COMUNICACAO,
    PROATIVIDADE,
    TRABALHO_EM_EQUIPE,
    LIDERANCA,
    ORGANIZACAO,
    RESOLUCAO_DE_PROBLEMAS,
    ADAPTABILIDADE,
    GESTAO_DE_TEMPO,
    NEGOCIACAO;
    /*
    // Ferramentas / Hard Skills
    LINGUA_INGLESA,
    FERRAMENTAS_DE_CRM_OU_ERP,
    METODOLOGIAS_AGEIS_SCRUM,
    FINANCAS_PESSOAIS_E_CONTROLE,
    ATENDIMENTO_AO_CLIENTE,
    DIREITO_EMPRESARIAL,
    */
}