package com.evoluirmais.evoluirmaisapi.model.enums;

public enum Profissao {
    ENGENHEIRO_DE_SOFTWARE,
    DESENVOLVEDOR_MOBILE,
    ANALISTA_DE_DADOS,
    DESIGNER_UX_UI,
    TECNICO_EM_INFORMATICA,
    MARKETING_DIGITAL,
    GERENTE_DE_PROJETOS,
    ENGENHEIRO_CIVIL,
    ARQUITETO,
    MEDICO,
    ENFERMEIRO,
    PSICOLOGO,
    PROFESSOR,
    ADVOGADO,
    ANALISTA_FINANCEIRO,
    CONSULTOR_DE_VENDAS,
    ELETRICISTA,
    MECANICO;
}